m <- read.table("s2.csv", sep=",", header=T, as.is=T)

x <- subset(m, rule.ant=="f")
z <- subset(m, rule.ant=="f:m")
n <- subset(m, rule.ant=="m:f")

m$sup100 <- m$supp*100
m <- subset(m, is.na(conv)==F)
m$rule <- paste(m$rule.ant,":", m$rule.con)


png('Insert Your Directory Path Here/savings.png')
plot(lift~supp, main = 'Lift-Support chart for f:.', data = subset(m, rule.ant=="f:m"), ylim=c(0,3.5))

with(subset(m, rule.ant=="f:m"), text(lift~supp, labels = subset(m, rule.ant=="f")$rule.con, pos = 4))
#points(lift~supp, data = subset(m, rule.ant=="f:m"), col="green")

#with(subset(m, rule.ant=="f:m"), text(lift~supp, labels = subset(m, rule.ant=="f:m")$rule.con, pos = 4, col="green"))

points(lift~supp, data = subset(m, rule.ant=="f:c"), col="blue")

with(subset(m, rule.ant=="f:c"), text(lift~supp, labels = subset(m, rule.ant=="f:c")$rule.con, pos = 4, col="blue"))

points(lift~supp, data = subset(m, rule.ant=="f:i"), col="purple")

with(subset(m, rule.ant=="f:i"), text(lift~supp, labels = subset(m, rule.ant=="f:i")$rule.con, pos = 4, col="purple"))

points(lift~supp, data = subset(m, rule.ant=="f:p"), col="orange")

with(subset(m, rule.ant=="f:p"), text(lift~supp, labels = subset(m, rule.ant=="f:p")$rule.con, pos = 4, col="orange"))

points(lift~supp, data = subset(m, rule.ant=="f:s"), col="gold")

with(subset(m, rule.ant=="f:s"), text(lift~supp, labels = subset(m, rule.ant=="f:s")$rule.con, pos = 4, col="gold"))

abline(h=1, col="red")
dev.off()

cols <- c("gold", "yellow", "red3", "darkorange", "cyan", "darkturquoise","blue", "deepskyblue","black", "purple",  "aquamarine", "mediumaquamarine", "forestgreen", "limegreen", "magenta", "orchid1")

text <- c("c", "C", "f", "F","i", "I", "io", "IO", "m", "M", "p", "P", "po", "PO", "s", "S") 


cols <- c("black","gold", "yellow", "red3", "darkorange", "cyan", "darkturquoise","blue", "deepskyblue","darkviolet", "purple",  "aquamarine", "mediumaquamarine", "forestgreen", "limegreen", "magenta", "orchid1")

text <- c("f", "f:c", "f:C", "f:f", "f:F","f:i", "f:I", "f:io", "f:IO", "f:m", "f:M", "f:p", "f:P", "f:po", "f:PO", "f:s", "f:S") 

plot(lift~sup100, data=x, col=cols[as.factor(rule.ant)], pch=8, xlab="support*100", ylab="lift", xlim=c(0,2.00))
legend("topright", legend=text, fill=cols, cex=0.8)
with(x, text(lift~sup100, labels = rule, pos = 4, col=cols[as.factor(rule.ant)], cex=0.6))
abline(h=1, col="red")


pdf("rules.pdf", 11,7)
plot(lift~sup100, data=m, col=cols[as.factor(rule.con)], pch=8, xlab="support*100", ylab="lift", xlim=c(0,2.00))
legend("topright", legend=text, fill=cols, cex=0.8)
with(m, text(lift~sup100, labels = rule, pos = 4, col=cols[as.factor(rule.con)], cex=0.6))
abline(h=1, col="red")
dev.off()

library(dplyr)
library(tidyr)
m$rule1 <- paste(m$rule.ant,":", m$rule.con)
m <- m %>% separate(rule1, c("first", "second"), ":", extra="drop")

x <- subset(m, first == "f" | first == "f "| first == "F" | first =="F ")

pdf("rules_f_ant.pdf", 11,7)
plot(lift~sup100, data=x, col=cols[as.factor(rule.con)], pch=8, xlab="support*100", ylab="lift", xlim=c(0,1.1), main="Rules with following as antecedent")
legend("topright", legend=text, fill=cols, cex=0.8)
with(x, text(lift~sup100, labels = rule, pos = 4, col=cols[as.factor(rule.con)], cex=0.6))
abline(h=1, col="red")
dev.off()

cols <- c("black","gold", "yellow", "red3", "darkorange", "cyan", "darkturquoise","blue", "deepskyblue","darkviolet", "purple",  "aquamarine", "mediumaquamarine", "forestgreen", "limegreen", "magenta", "orchid1")

text <- c("f", "f:c", "f:C", "f:f", "f:F","f:i", "f:I", "f:io", "f:IO", "f:m", "f:M", "f:p", "f:P", "f:po", "f:PO", "f:s", "f:S") 

plot(lift~sup100, data=x, col=cols[as.factor(rule.ant)], pch=8, xlab="support*100", ylab="lift", xlim=c(0,1.1), main="Rules with following as antecedent")
legend("topright", legend=text, fill=cols, cex=0.8)
with(x, text(lift~sup100, labels = rule, pos = 4, col=cols[as.factor(rule.ant)], cex=0.6))
abline(h=1, col="red")

x <- subset(m, first == "m" | first == "m "| first == "M" | first =="M ")

pdf("rules_m_ant.pdf", 11,7)
plot(lift~sup100, data=x, col=cols[as.factor(rule.con)], pch=8, xlab="support*100", ylab="lift", xlim=c(0,1.3), main="Rules with forking as antecedent")
legend("topright", legend=text, fill=cols, cex=0.8)
with(x, text(lift~sup100, labels = rule, pos = 4, col=cols[as.factor(rule.con)], cex=0.6))
abline(h=1, col="red")
dev.off()

x <- subset(m, first == "p" | first == "p "| first == "P" | first =="P ")

pdf("rules_p_ant.pdf", 11,7)
plot(lift~sup100, data=x, col=cols[as.factor(rule.con)], pch=8, xlab="support*100", ylab="lift", xlim=c(0,1.3), main="Rules with pull request as antecedent")
legend("topright", legend=text, fill=cols, cex=0.8)
with(x, text(lift~sup100, labels = rule, pos = 4, col=cols[as.factor(rule.con)], cex=0.6))
abline(h=1, col="red")
dev.off()

x <- subset(m, first == "s" | first == "s "| first == "S" | first =="S ")

pdf("rules_s_ant.pdf", 11,7)
plot(lift~sup100, data=x, col=cols[as.factor(rule.con)], pch=8, xlab="support*100", ylab="lift", xlim=c(0,1.0), main="Rules with starring as antecedent")
legend("topright", legend=text, fill=cols, cex=0.8)
with(x, text(lift~sup100, labels = rule, pos = 4, col=cols[as.factor(rule.con)], cex=0.6))
abline(h=1, col="red")
dev.off()

x <- subset(m, first == "i" | first == "i "| first == "I" | first =="I ")

pdf("rules_i_ant.pdf", 11,7)
plot(lift~sup100, data=x, col=cols[as.factor(rule.con)], pch=8, xlab="support*100", ylab="lift", xlim=c(0,1.0), main="Rules with opening an issue as antecedent")
legend("topright", legend=text, fill=cols, cex=0.8)
with(x, text(lift~sup100, labels = rule, pos = 4, col=cols[as.factor(rule.con)], cex=0.6))
abline(h=1, col="red")
dev.off()

x <- subset(m, rule.ant=="f")
summary(x$lift)
x <- subset(m, rule.ant=="f:c")
summary(x$lift)
x <- subset(m, rule.ant=="f:C")
summary(x$lift)
x <- subset(m, rule.ant=="f:f")
summary(x$lift)
x <- subset(m, rule.ant=="f:F")
summary(x$lift)
x <- subset(m, rule.ant=="f:i")
summary(x$lift)
x <- subset(m, rule.ant=="f:I")
summary(x$lift)
x <- subset(m, rule.ant=="f:io")
summary(x$lift)
x <- subset(m, rule.ant=="f:IO")
summary(x$lift)
x <- subset(m, rule.ant=="f:m")
summary(x$lift)
x <- subset(m, rule.ant=="f:M")
summary(x$lift)
x <- subset(m, rule.ant=="f:p")
summary(x$lift)
x <- subset(m, rule.ant=="f:P")
summary(x$lift)
x <- subset(m, rule.ant=="f:po")
summary(x$lift)
x <- subset(m, rule.ant=="f:PO")
summary(x$lift)
x <- subset(m, rule.ant=="f:s")
summary(x$lift)
x <- subset(m, rule.ant=="f:S")
summary(x$lift)


x <- subset(m, rule.ant=="f")
summary(x$lift)
x <- subset(m, rule.ant=="c:f")
summary(x$lift)
x <- subset(m, rule.ant=="c:F")
summary(x$lift)
x <- subset(m, rule.ant=="f:f")
summary(x$lift)
x <- subset(m, rule.ant=="f:F")
summary(x$lift)
x <- subset(m, rule.ant=="i:f")
summary(x$lift)
x <- subset(m, rule.ant=="i:F")
summary(x$lift)
x <- subset(m, rule.ant=="io:f")
summary(x$lift)
x <- subset(m, rule.ant=="io:F")
summary(x$lift)
x <- subset(m, rule.ant=="m:f")
summary(x$lift)
x <- subset(m, rule.ant=="m:F")
summary(x$lift)
x <- subset(m, rule.ant=="p:f")
summary(x$lift)
x <- subset(m, rule.ant=="p:F")
summary(x$lift)
x <- subset(m, rule.ant=="po:f")
summary(x$lift)
x <- subset(m, rule.ant=="po:F")
summary(x$lift)
x <- subset(m, rule.ant=="s:f")
summary(x$lift)
x <- subset(m, rule.ant=="s:F")
summary(x$lift)

x <- subset(m, rule.ant=="m")
summary(x$lift)
x <- subset(m, rule.ant=="c:m")
summary(x$lift)
x <- subset(m, rule.ant=="c:M")
summary(x$lift)
x <- subset(m, rule.ant=="f:m")
summary(x$lift)
x <- subset(m, rule.ant=="f:M")
summary(x$lift)
x <- subset(m, rule.ant=="i:m")
summary(x$lift)
x <- subset(m, rule.ant=="i:M")
summary(x$lift)
x <- subset(m, rule.ant=="io:m")
summary(x$lift)
x <- subset(m, rule.ant=="io:M")
summary(x$lift)
x <- subset(m, rule.ant=="m:m")
summary(x$lift)
x <- subset(m, rule.ant=="m:M")
summary(x$lift)
x <- subset(m, rule.ant=="p:m")
summary(x$lift)
x <- subset(m, rule.ant=="p:M")
summary(x$lift)
x <- subset(m, rule.ant=="po:m")
summary(x$lift)
x <- subset(m, rule.ant=="po:M")
summary(x$lift)
x <- subset(m, rule.ant=="s:m")
summary(x$lift)
x <- subset(m, rule.ant=="s:M")
summary(x$lift)
